//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalHouse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentalHouseEntities : DbContext
    {
        public RentalHouseEntities()
            : base("name=RentalHouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactRecord> ContactRecords { get; set; }
        public virtual DbSet<CustomerRecord> CustomerRecords { get; set; }
        public virtual DbSet<HouseRecord> HouseRecords { get; set; }
    }
}
